Adding view model class and integrating with view classes
SamilaRuane/ChuckNorrisFacts pull request #10
Opened 2018-08-08 15:15 UTC by SamilaRuane

### :pushpin: Referências

* **Repositório da Atividade:** [Ex03](https://github.com/stone-payments/mobile-training/blob/master/ex03-chucknorris.md) 

### :cyclone: Mudanças

Este PR adiciona a classe de view model da feature de pesquisa de fatos e faz as integrações necessárias com a activity. 

Neste momento a classe _SearchFactRepositoryMock_ está sendo usada para simular a comunicação com a camada de dados. 
 
### :art: Mudanças de UI
Foi ajustado o alinhamento do texto no item da lista e adicionado cores diferentes no background dependendo da categoria. Também foi adicionado o ajuste da fonte do texto de acordo com o comprimento da string da propriedade description do objeto da classe _Fact_.

### :memo: Notas

NA

2018-08-08 20:16 UTC, AllanHasegawa requested changes
Só algumas coisas pequenas.

2018-08-08 20:16 UTC, AllanHasegawa commented on app/src/main/java/br/stone/mobiletraining/samilasantos/chucknorrisfacts/common/groupieItems.kt
> +    private val regularSize = 14
Acho melhor deixar esses valores num arquivo de dimens do Android.

2018-08-08 20:16 UTC, AllanHasegawa commented on app/src/main/java/br/stone/mobiletraining/samilasantos/chucknorrisfacts/screenSearchFact/SearchFactActivity.kt
> +    private val viewModel by diInject<SearchFactViewModel>()
Esse ViewModel não está sendo injetado com o `ViewModelProvider`. É esse carinha que mantem a instância do ViewModel de forma correta com o lifecycle da Activity:

https://developer.android.com/topic/libraries/architecture/viewmodel

Se quiser spoilers de como resolver isso só avisar xD

2018-08-08 20:16 UTC, AllanHasegawa commented on app/src/main/java/br/stone/mobiletraining/samilasantos/chucknorrisfacts/screenSearchFact/SearchFactActivity.kt
> +            groupAdapter.add(InitialGroup())
A view aqui não está sendo passiva nesse momento.

Podemos facilmente delegar a criação desse valor inicial pro "ViewModel" e deixar ele controlar todos os estados da view.

2018-08-08 20:16 UTC, AllanHasegawa commented on app/src/main/java/br/stone/mobiletraining/samilasantos/chucknorrisfacts/screenSearchFact/SearchFactViewModel.kt
> +        .switchMap {
:+1:

2018-08-08 20:16 UTC, AllanHasegawa commented on app/src/main/java/br/stone/mobiletraining/samilasantos/chucknorrisfacts/screenSearchFact/SearchFactViewModel.kt
> +        .throttleFirst(500, TimeUnit.MILLISECONDS)
:+1:

2018-08-08 23:15 UTC, SamilaRuane commented on app/src/main/java/br/stone/mobiletraining/samilasantos/chucknorrisfacts/screenSearchFact/SearchFactViewModel.kt
>          .switchMap {
Enquanto eu estava adicionando o view model provider, percebi que eu não estava mantendo o estado da view em lugar nenhum e quando rodava a tela ela voltava para o estado inicial, então criei uma variável que mantém o estado, mas quem a modifica é a activity chamando o evento stateWasChanged(). Como esse evento é chamado no subscribe acredito que não está gerando efeito colateral, você concorda?

2018-08-09 12:52 UTC, AllanHasegawa requested changes
Coisas simples again :)

2018-08-09 12:52 UTC, AllanHasegawa commented on app/src/main/res/values/dimens.xml
> +    <dimen name="regular_font_size">14dp</dimen>
Vc pode armazenar a fonte em "sp" mesmo, assim evita ter que converter de "dp" para "sp" no código.

2018-08-09 12:52 UTC, AllanHasegawa commented on app/src/main/java/br/stone/mobiletraining/samilasantos/chucknorrisfacts/screenSearchFact/SearchFactViewModel.kt
>          .switchMap {
Nesse caso o `state` está fazendo um "round-trip" desnecessário.

Se o ViewModel é quem está enviando os `state` pra view, pq que a view tem que avisar pro ViewModel que ela recebeu um novo estado?

Mas respondendo a sua pergunta. Ainda sim é um efeito colateral pois um comportamento fora da stream (está no subscribe) está alterando output da stream. Porém, nem todo side-effect é super vilão xD Vamos ter sim efeitos colaterais em alguns casos. O importante é identificar quais são super problemáticos e quais não são. Geralmente efeitos colaterais que envolvem mais de uma stream são um grande "no-no".

Enfim, nesse caso aqui eu acredito que um efeito colateral dentro do ViewModel para salvar o estado inicial seja okay. Portanto que ele seja usado só para essa stream.

2018-08-09 14:02 UTC, SamilaRuane commented on app/src/main/java/br/stone/mobiletraining/samilasantos/chucknorrisfacts/screenSearchFact/SearchFactViewModel.kt
>          .switchMap {
Mesmo mudando para sp foi necessário fazer a divisão pela densidade da tela, sem isso a letra ficava muito grande.

2018-08-09 21:38 UTC, AllanHasegawa approved these changes
:rocket:

2018-08-09 23:42 UTC, merged